// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ptphat03/Fish-Game/services/game-server/internal/repository"
	gameHttp "github.com/ptphat03/Fish-Game/services/game-server/internal/transport/http"
	"github.com/ptphat03/Fish-Game/services/game-server/internal/usecase"
	"github.com/ptphat03/Fish-Game/services/game-server/internal/ws"
	"github.com/ptphat03/Fish-Game/services/game-server/pkg/utils"
	"github.com/jackc/pgx/v5/pgxpool"
)

func InitializeApp(db *pgxpool.Pool, tokenMaker utils.TokenMaker) (gameHttp.Handlers, error) {
	// Repos — vẫn cần cho WS game engine (không expose qua HTTP nữa)
	roomRepository   := repository.NewRoomRepository(db)
	fishRepository   := repository.NewFishRepository(db)
	walletRepository := repository.NewWalletRepository(db)

	// Usecases — WS client dùng trực tiếp để validate room, spawn fish, manage session
	roomUsecase   := usecase.NewRoomUsecase(roomRepository)
	fishUsecase   := usecase.NewFishUsecase(fishRepository)
	walletUsecase := usecase.NewWalletUsecase(walletRepository)

	hub       := ws.NewHub(fishUsecase)
	wsHandler := gameHttp.NewWSHandler(hub, walletUsecase, roomUsecase, fishUsecase, tokenMaker)

	return gameHttp.Handlers{WS: wsHandler}, nil
}
