// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fishes.sql

package dbgen

import (
	"context"
)

const createFish = `-- name: CreateFish :one
INSERT INTO fishes (name, health, reward_multiplier, base_prob, speed, asset_path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, health, reward_multiplier, base_prob, speed, asset_path, created_at, updated_at
`

type CreateFishParams struct {
	Name             string
	Health           int32
	RewardMultiplier int32
	BaseProb         float64
	Speed            float64
	AssetPath        string
}

func (q *Queries) CreateFish(ctx context.Context, arg CreateFishParams) (Fish, error) {
	row := q.db.QueryRow(ctx, createFish,
		arg.Name,
		arg.Health,
		arg.RewardMultiplier,
		arg.BaseProb,
		arg.Speed,
		arg.AssetPath,
	)
	var i Fish
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Health,
		&i.RewardMultiplier,
		&i.BaseProb,
		&i.Speed,
		&i.AssetPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFish = `-- name: DeleteFish :one
DELETE FROM fishes
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteFish(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteFish, id)
	var id_2 int32
	err := row.Scan(&id_2)
	return id_2, err
}

const getFishByID = `-- name: GetFishByID :one
SELECT id, name, health, reward_multiplier, base_prob, speed, asset_path, created_at, updated_at
FROM fishes
WHERE id = $1
`

func (q *Queries) GetFishByID(ctx context.Context, id int32) (Fish, error) {
	row := q.db.QueryRow(ctx, getFishByID, id)
	var i Fish
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Health,
		&i.RewardMultiplier,
		&i.BaseProb,
		&i.Speed,
		&i.AssetPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFishes = `-- name: ListFishes :many
SELECT id, name, health, reward_multiplier, base_prob, speed, asset_path, created_at, updated_at
FROM fishes
ORDER BY reward_multiplier ASC
`

func (q *Queries) ListFishes(ctx context.Context) ([]Fish, error) {
	rows, err := q.db.Query(ctx, listFishes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fish
	for rows.Next() {
		var i Fish
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Health,
			&i.RewardMultiplier,
			&i.BaseProb,
			&i.Speed,
			&i.AssetPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFish = `-- name: UpdateFish :one
UPDATE fishes
SET name = $1, health = $2, reward_multiplier = $3, base_prob = $4, speed = $5, asset_path = $6, updated_at = NOW()
WHERE id = $7
RETURNING id, name, health, reward_multiplier, base_prob, speed, asset_path, created_at, updated_at
`

type UpdateFishParams struct {
	Name             string
	Health           int32
	RewardMultiplier int32
	BaseProb         float64
	Speed            float64
	AssetPath        string
	ID               int32
}

func (q *Queries) UpdateFish(ctx context.Context, arg UpdateFishParams) (Fish, error) {
	row := q.db.QueryRow(ctx, updateFish,
		arg.Name,
		arg.Health,
		arg.RewardMultiplier,
		arg.BaseProb,
		arg.Speed,
		arg.AssetPath,
		arg.ID,
	)
	var i Fish
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Health,
		&i.RewardMultiplier,
		&i.BaseProb,
		&i.Speed,
		&i.AssetPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
