// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_sessions.sql

package dbgen

import (
	"context"
)

const closeOrphanedSessions = `-- name: CloseOrphanedSessions :exec
UPDATE game_sessions
SET status = 'finished', ended_at = NOW()
WHERE user_id = $1
  AND status = 'active'
`

func (q *Queries) CloseOrphanedSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, closeOrphanedSessions, userID)
	return err
}

const createGameSession = `-- name: CreateGameSession :one
INSERT INTO game_sessions (user_id, room_id)
VALUES ($1, $2)
RETURNING id, user_id, room_id, shots_fired, fish_killed, total_spend, total_earn, status, started_at, ended_at
`

type CreateGameSessionParams struct {
	UserID int64
	RoomID int64
}

func (q *Queries) CreateGameSession(ctx context.Context, arg CreateGameSessionParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, createGameSession, arg.UserID, arg.RoomID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.ShotsFired,
		&i.FishKilled,
		&i.TotalSpend,
		&i.TotalEarn,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const endGameSession = `-- name: EndGameSession :one
UPDATE game_sessions
SET status      = 'finished',
    shots_fired = $2,
    fish_killed = $3,
    total_spend = $4,
    total_earn  = $5,
    ended_at    = NOW()
WHERE id = $1
  AND status = 'active'
RETURNING id, user_id, room_id, shots_fired, fish_killed, total_spend, total_earn, status, started_at, ended_at
`

type EndGameSessionParams struct {
	ID         int64
	ShotsFired int32
	FishKilled int32
	TotalSpend int64
	TotalEarn  int64
}

func (q *Queries) EndGameSession(ctx context.Context, arg EndGameSessionParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, endGameSession,
		arg.ID,
		arg.ShotsFired,
		arg.FishKilled,
		arg.TotalSpend,
		arg.TotalEarn,
	)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.ShotsFired,
		&i.FishKilled,
		&i.TotalSpend,
		&i.TotalEarn,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getGameSessionByID = `-- name: GetGameSessionByID :one
SELECT id, user_id, room_id, shots_fired, fish_killed, total_spend, total_earn, status, started_at, ended_at
FROM game_sessions
WHERE id = $1
`

func (q *Queries) GetGameSessionByID(ctx context.Context, id int64) (GameSession, error) {
	row := q.db.QueryRow(ctx, getGameSessionByID, id)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.ShotsFired,
		&i.FishKilled,
		&i.TotalSpend,
		&i.TotalEarn,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listGameSessionsByUserID = `-- name: ListGameSessionsByUserID :many
SELECT id, user_id, room_id, shots_fired, fish_killed, total_spend, total_earn, status, started_at, ended_at
FROM game_sessions
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListGameSessionsByUserIDParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListGameSessionsByUserID(ctx context.Context, arg ListGameSessionsByUserIDParams) ([]GameSession, error) {
	rows, err := q.db.Query(ctx, listGameSessionsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameSession
	for rows.Next() {
		var i GameSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoomID,
			&i.ShotsFired,
			&i.FishKilled,
			&i.TotalSpend,
			&i.TotalEarn,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
