// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Fish struct {
	ID               int32
	Name             string
	Health           int32
	RewardMultiplier int32
	BaseProb         float64
	Speed            float64
	AssetPath        string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type GameSession struct {
	ID         int64
	UserID     int64
	RoomID     int64
	ShotsFired int32
	FishKilled int32
	TotalSpend int64
	TotalEarn  int64
	Status     string
	StartedAt  pgtype.Timestamptz
	EndedAt    pgtype.Timestamptz
}

type Room struct {
	ID          int64
	Name        string
	MaxPlayers  int32
	Description pgtype.Text
	Rtp         float64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Transaction struct {
	ID          int64
	UserID      int64
	SessionID   pgtype.Int8
	Amount      int64
	Type        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type Wallet struct {
	UserID    int64
	Balance   int64
	UpdatedAt pgtype.Timestamptz
}
