// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, max_players, description, rtp)
VALUES ($1, $2, $3, $4)
RETURNING id, name, max_players, description, rtp, created_at, updated_at
`

type CreateRoomParams struct {
	Name        string
	MaxPlayers  int32
	Description pgtype.Text
	Rtp         float64
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.Name,
		arg.MaxPlayers,
		arg.Description,
		arg.Rtp,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MaxPlayers,
		&i.Description,
		&i.Rtp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :one
DELETE FROM rooms
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteRoom(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteRoom, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, max_players, description, rtp, created_at, updated_at
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MaxPlayers,
		&i.Description,
		&i.Rtp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, max_players, description, rtp, created_at, updated_at
FROM rooms
ORDER BY id ASC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MaxPlayers,
			&i.Description,
			&i.Rtp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET name = $1, max_players = $2, description = $3, rtp = $4, updated_at = NOW()
WHERE id = $5
RETURNING id, name, max_players, description, rtp, created_at, updated_at
`

type UpdateRoomParams struct {
	Name        string
	MaxPlayers  int32
	Description pgtype.Text
	Rtp         float64
	ID          int64
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.Name,
		arg.MaxPlayers,
		arg.Description,
		arg.Rtp,
		arg.ID,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MaxPlayers,
		&i.Description,
		&i.Rtp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
