// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: fish_game.proto

package fishgamepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_fish_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type ClientReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientReadyRequest) Reset() {
	*x = ClientReadyRequest{}
	mi := &file_fish_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReadyRequest) ProtoMessage() {}

func (x *ClientReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReadyRequest.ProtoReflect.Descriptor instead.
func (*ClientReadyRequest) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{1}
}

type ShootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PosX          float32                `protobuf:"fixed32,1,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float32                `protobuf:"fixed32,2,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Angle         float32                `protobuf:"fixed32,3,opt,name=angle,proto3" json:"angle,omitempty"`
	BetAmount     int64                  `protobuf:"varint,4,opt,name=bet_amount,json=betAmount,proto3" json:"bet_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShootRequest) Reset() {
	*x = ShootRequest{}
	mi := &file_fish_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootRequest) ProtoMessage() {}

func (x *ShootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootRequest.ProtoReflect.Descriptor instead.
func (*ShootRequest) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{2}
}

func (x *ShootRequest) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *ShootRequest) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *ShootRequest) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *ShootRequest) GetBetAmount() int64 {
	if x != nil {
		return x.BetAmount
	}
	return 0
}

type HitFishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FishId        int32                  `protobuf:"varint,1,opt,name=fish_id,json=fishId,proto3" json:"fish_id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitFishRequest) Reset() {
	*x = HitFishRequest{}
	mi := &file_fish_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitFishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitFishRequest) ProtoMessage() {}

func (x *HitFishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitFishRequest.ProtoReflect.Descriptor instead.
func (*HitFishRequest) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{3}
}

func (x *HitFishRequest) GetFishId() int32 {
	if x != nil {
		return x.FishId
	}
	return 0
}

func (x *HitFishRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_fish_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{4}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_fish_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{5}
}

type SessionStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SeatId        int32                  `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStartedEvent) Reset() {
	*x = SessionStartedEvent{}
	mi := &file_fish_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartedEvent) ProtoMessage() {}

func (x *SessionStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartedEvent.ProtoReflect.Descriptor instead.
func (*SessionStartedEvent) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{6}
}

func (x *SessionStartedEvent) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *SessionStartedEvent) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *SessionStartedEvent) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type ShootAckEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShotsFired    int64                  `protobuf:"varint,1,opt,name=shots_fired,json=shotsFired,proto3" json:"shots_fired,omitempty"`
	TotalSpend    int64                  `protobuf:"varint,2,opt,name=total_spend,json=totalSpend,proto3" json:"total_spend,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShootAckEvent) Reset() {
	*x = ShootAckEvent{}
	mi := &file_fish_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShootAckEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootAckEvent) ProtoMessage() {}

func (x *ShootAckEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootAckEvent.ProtoReflect.Descriptor instead.
func (*ShootAckEvent) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{7}
}

func (x *ShootAckEvent) GetShotsFired() int64 {
	if x != nil {
		return x.ShotsFired
	}
	return 0
}

func (x *ShootAckEvent) GetTotalSpend() int64 {
	if x != nil {
		return x.TotalSpend
	}
	return 0
}

func (x *ShootAckEvent) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type HitResultEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Killed        bool                   `protobuf:"varint,1,opt,name=killed,proto3" json:"killed,omitempty"`
	FishId        int32                  `protobuf:"varint,2,opt,name=fish_id,json=fishId,proto3" json:"fish_id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Earn          int64                  `protobuf:"varint,4,opt,name=earn,proto3" json:"earn,omitempty"`       // reward (only when killed=true)
	Balance       int64                  `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"` // updated balance
	TotalEarn     int64                  `protobuf:"varint,6,opt,name=total_earn,json=totalEarn,proto3" json:"total_earn,omitempty"`
	FishKilled    int32                  `protobuf:"varint,7,opt,name=fish_killed,json=fishKilled,proto3" json:"fish_killed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitResultEvent) Reset() {
	*x = HitResultEvent{}
	mi := &file_fish_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitResultEvent) ProtoMessage() {}

func (x *HitResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitResultEvent.ProtoReflect.Descriptor instead.
func (*HitResultEvent) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{8}
}

func (x *HitResultEvent) GetKilled() bool {
	if x != nil {
		return x.Killed
	}
	return false
}

func (x *HitResultEvent) GetFishId() int32 {
	if x != nil {
		return x.FishId
	}
	return 0
}

func (x *HitResultEvent) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HitResultEvent) GetEarn() int64 {
	if x != nil {
		return x.Earn
	}
	return 0
}

func (x *HitResultEvent) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *HitResultEvent) GetTotalEarn() int64 {
	if x != nil {
		return x.TotalEarn
	}
	return 0
}

func (x *HitResultEvent) GetFishKilled() int32 {
	if x != nil {
		return x.FishKilled
	}
	return 0
}

type SessionEndedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalBalance  int64                  `protobuf:"varint,1,opt,name=final_balance,json=finalBalance,proto3" json:"final_balance,omitempty"`
	TotalEarn     int64                  `protobuf:"varint,2,opt,name=total_earn,json=totalEarn,proto3" json:"total_earn,omitempty"`
	TotalSpend    int64                  `protobuf:"varint,3,opt,name=total_spend,json=totalSpend,proto3" json:"total_spend,omitempty"`
	FishKilled    int32                  `protobuf:"varint,4,opt,name=fish_killed,json=fishKilled,proto3" json:"fish_killed,omitempty"`
	ShotsFired    int32                  `protobuf:"varint,5,opt,name=shots_fired,json=shotsFired,proto3" json:"shots_fired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEndedEvent) Reset() {
	*x = SessionEndedEvent{}
	mi := &file_fish_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEndedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEndedEvent) ProtoMessage() {}

func (x *SessionEndedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEndedEvent.ProtoReflect.Descriptor instead.
func (*SessionEndedEvent) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{9}
}

func (x *SessionEndedEvent) GetFinalBalance() int64 {
	if x != nil {
		return x.FinalBalance
	}
	return 0
}

func (x *SessionEndedEvent) GetTotalEarn() int64 {
	if x != nil {
		return x.TotalEarn
	}
	return 0
}

func (x *SessionEndedEvent) GetTotalSpend() int64 {
	if x != nil {
		return x.TotalSpend
	}
	return 0
}

func (x *SessionEndedEvent) GetFishKilled() int32 {
	if x != nil {
		return x.FishKilled
	}
	return 0
}

func (x *SessionEndedEvent) GetShotsFired() int32 {
	if x != nil {
		return x.ShotsFired
	}
	return 0
}

type SpawnFishEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	FishId        int32                  `protobuf:"varint,2,opt,name=fish_id,json=fishId,proto3" json:"fish_id,omitempty"`
	PathId        int32                  `protobuf:"varint,3,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	SpawnTime     int64                  `protobuf:"varint,4,opt,name=spawn_time,json=spawnTime,proto3" json:"spawn_time,omitempty"` // Unix milliseconds
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`                    // max lifetime in seconds
	Speed         float32                `protobuf:"fixed32,6,opt,name=speed,proto3" json:"speed,omitempty"`                         // animation speed hint for Unity
	AssetPath     string                 `protobuf:"bytes,7,opt,name=asset_path,json=assetPath,proto3" json:"asset_path,omitempty"`  // texture path for Unity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnFishEvent) Reset() {
	*x = SpawnFishEvent{}
	mi := &file_fish_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnFishEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnFishEvent) ProtoMessage() {}

func (x *SpawnFishEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnFishEvent.ProtoReflect.Descriptor instead.
func (*SpawnFishEvent) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{10}
}

func (x *SpawnFishEvent) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SpawnFishEvent) GetFishId() int32 {
	if x != nil {
		return x.FishId
	}
	return 0
}

func (x *SpawnFishEvent) GetPathId() int32 {
	if x != nil {
		return x.PathId
	}
	return 0
}

func (x *SpawnFishEvent) GetSpawnTime() int64 {
	if x != nil {
		return x.SpawnTime
	}
	return 0
}

func (x *SpawnFishEvent) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SpawnFishEvent) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *SpawnFishEvent) GetAssetPath() string {
	if x != nil {
		return x.AssetPath
	}
	return ""
}

type BroadcastShootEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        int32                  `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	PosX          float32                `protobuf:"fixed32,2,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float32                `protobuf:"fixed32,3,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Angle         float32                `protobuf:"fixed32,4,opt,name=angle,proto3" json:"angle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastShootEvent) Reset() {
	*x = BroadcastShootEvent{}
	mi := &file_fish_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastShootEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastShootEvent) ProtoMessage() {}

func (x *BroadcastShootEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastShootEvent.ProtoReflect.Descriptor instead.
func (*BroadcastShootEvent) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{11}
}

func (x *BroadcastShootEvent) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *BroadcastShootEvent) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *BroadcastShootEvent) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *BroadcastShootEvent) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

type BroadcastKillEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	SeatId        int32                  `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastKillEvent) Reset() {
	*x = BroadcastKillEvent{}
	mi := &file_fish_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastKillEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastKillEvent) ProtoMessage() {}

func (x *BroadcastKillEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastKillEvent.ProtoReflect.Descriptor instead.
func (*BroadcastKillEvent) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{12}
}

func (x *BroadcastKillEvent) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *BroadcastKillEvent) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_fish_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{13}
}

func (x *ErrorEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PongEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongEvent) Reset() {
	*x = PongEvent{}
	mi := &file_fish_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongEvent) ProtoMessage() {}

func (x *PongEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongEvent.ProtoReflect.Descriptor instead.
func (*PongEvent) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{14}
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_JoinRoom
	//	*Envelope_ClientReady
	//	*Envelope_Shoot
	//	*Envelope_HitFish
	//	*Envelope_LeaveRoom
	//	*Envelope_Ping
	//	*Envelope_SessionStarted
	//	*Envelope_ShootAck
	//	*Envelope_HitResult
	//	*Envelope_SessionEnded
	//	*Envelope_SpawnFish
	//	*Envelope_BroadcastShoot
	//	*Envelope_BroadcastKill
	//	*Envelope_Error
	//	*Envelope_Pong
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_fish_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_fish_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_fish_game_proto_rawDescGZIP(), []int{15}
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetJoinRoom() *JoinRoomRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *Envelope) GetClientReady() *ClientReadyRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ClientReady); ok {
			return x.ClientReady
		}
	}
	return nil
}

func (x *Envelope) GetShoot() *ShootRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Shoot); ok {
			return x.Shoot
		}
	}
	return nil
}

func (x *Envelope) GetHitFish() *HitFishRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HitFish); ok {
			return x.HitFish
		}
	}
	return nil
}

func (x *Envelope) GetLeaveRoom() *LeaveRoomRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_LeaveRoom); ok {
			return x.LeaveRoom
		}
	}
	return nil
}

func (x *Envelope) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetSessionStarted() *SessionStartedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SessionStarted); ok {
			return x.SessionStarted
		}
	}
	return nil
}

func (x *Envelope) GetShootAck() *ShootAckEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ShootAck); ok {
			return x.ShootAck
		}
	}
	return nil
}

func (x *Envelope) GetHitResult() *HitResultEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HitResult); ok {
			return x.HitResult
		}
	}
	return nil
}

func (x *Envelope) GetSessionEnded() *SessionEndedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SessionEnded); ok {
			return x.SessionEnded
		}
	}
	return nil
}

func (x *Envelope) GetSpawnFish() *SpawnFishEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SpawnFish); ok {
			return x.SpawnFish
		}
	}
	return nil
}

func (x *Envelope) GetBroadcastShoot() *BroadcastShootEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_BroadcastShoot); ok {
			return x.BroadcastShoot
		}
	}
	return nil
}

func (x *Envelope) GetBroadcastKill() *BroadcastKillEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_BroadcastKill); ok {
			return x.BroadcastKill
		}
	}
	return nil
}

func (x *Envelope) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Envelope) GetPong() *PongEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_JoinRoom struct {
	// client → server
	JoinRoom *JoinRoomRequest `protobuf:"bytes,1,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type Envelope_ClientReady struct {
	ClientReady *ClientReadyRequest `protobuf:"bytes,2,opt,name=client_ready,json=clientReady,proto3,oneof"`
}

type Envelope_Shoot struct {
	Shoot *ShootRequest `protobuf:"bytes,3,opt,name=shoot,proto3,oneof"`
}

type Envelope_HitFish struct {
	HitFish *HitFishRequest `protobuf:"bytes,4,opt,name=hit_fish,json=hitFish,proto3,oneof"`
}

type Envelope_LeaveRoom struct {
	LeaveRoom *LeaveRoomRequest `protobuf:"bytes,5,opt,name=leave_room,json=leaveRoom,proto3,oneof"`
}

type Envelope_Ping struct {
	Ping *PingRequest `protobuf:"bytes,6,opt,name=ping,proto3,oneof"`
}

type Envelope_SessionStarted struct {
	// server → client
	SessionStarted *SessionStartedEvent `protobuf:"bytes,10,opt,name=session_started,json=sessionStarted,proto3,oneof"`
}

type Envelope_ShootAck struct {
	ShootAck *ShootAckEvent `protobuf:"bytes,11,opt,name=shoot_ack,json=shootAck,proto3,oneof"`
}

type Envelope_HitResult struct {
	HitResult *HitResultEvent `protobuf:"bytes,12,opt,name=hit_result,json=hitResult,proto3,oneof"`
}

type Envelope_SessionEnded struct {
	SessionEnded *SessionEndedEvent `protobuf:"bytes,13,opt,name=session_ended,json=sessionEnded,proto3,oneof"`
}

type Envelope_SpawnFish struct {
	SpawnFish *SpawnFishEvent `protobuf:"bytes,14,opt,name=spawn_fish,json=spawnFish,proto3,oneof"`
}

type Envelope_BroadcastShoot struct {
	BroadcastShoot *BroadcastShootEvent `protobuf:"bytes,15,opt,name=broadcast_shoot,json=broadcastShoot,proto3,oneof"`
}

type Envelope_BroadcastKill struct {
	BroadcastKill *BroadcastKillEvent `protobuf:"bytes,16,opt,name=broadcast_kill,json=broadcastKill,proto3,oneof"`
}

type Envelope_Error struct {
	Error *ErrorEvent `protobuf:"bytes,17,opt,name=error,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong *PongEvent `protobuf:"bytes,18,opt,name=pong,proto3,oneof"`
}

func (*Envelope_JoinRoom) isEnvelope_Payload() {}

func (*Envelope_ClientReady) isEnvelope_Payload() {}

func (*Envelope_Shoot) isEnvelope_Payload() {}

func (*Envelope_HitFish) isEnvelope_Payload() {}

func (*Envelope_LeaveRoom) isEnvelope_Payload() {}

func (*Envelope_Ping) isEnvelope_Payload() {}

func (*Envelope_SessionStarted) isEnvelope_Payload() {}

func (*Envelope_ShootAck) isEnvelope_Payload() {}

func (*Envelope_HitResult) isEnvelope_Payload() {}

func (*Envelope_SessionEnded) isEnvelope_Payload() {}

func (*Envelope_SpawnFish) isEnvelope_Payload() {}

func (*Envelope_BroadcastShoot) isEnvelope_Payload() {}

func (*Envelope_BroadcastKill) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

func (*Envelope_Pong) isEnvelope_Payload() {}

var File_fish_game_proto protoreflect.FileDescriptor

const file_fish_game_proto_rawDesc = "" +
	"\n" +
	"\x0ffish_game.proto\x12\bfishgame\"*\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\"\x14\n" +
	"\x12ClientReadyRequest\"m\n" +
	"\fShootRequest\x12\x13\n" +
	"\x05pos_x\x18\x01 \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x02 \x01(\x02R\x04posY\x12\x14\n" +
	"\x05angle\x18\x03 \x01(\x02R\x05angle\x12\x1d\n" +
	"\n" +
	"bet_amount\x18\x04 \x01(\x03R\tbetAmount\"J\n" +
	"\x0eHitFishRequest\x12\x17\n" +
	"\afish_id\x18\x01 \x01(\x05R\x06fishId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\"\x12\n" +
	"\x10LeaveRoomRequest\"\r\n" +
	"\vPingRequest\"g\n" +
	"\x13SessionStartedEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x17\n" +
	"\aseat_id\x18\x02 \x01(\x05R\x06seatId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\"k\n" +
	"\rShootAckEvent\x12\x1f\n" +
	"\vshots_fired\x18\x01 \x01(\x03R\n" +
	"shotsFired\x12\x1f\n" +
	"\vtotal_spend\x18\x02 \x01(\x03R\n" +
	"totalSpend\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\"\xd0\x01\n" +
	"\x0eHitResultEvent\x12\x16\n" +
	"\x06killed\x18\x01 \x01(\bR\x06killed\x12\x17\n" +
	"\afish_id\x18\x02 \x01(\x05R\x06fishId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04earn\x18\x04 \x01(\x03R\x04earn\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x03R\abalance\x12\x1d\n" +
	"\n" +
	"total_earn\x18\x06 \x01(\x03R\ttotalEarn\x12\x1f\n" +
	"\vfish_killed\x18\a \x01(\x05R\n" +
	"fishKilled\"\xba\x01\n" +
	"\x11SessionEndedEvent\x12#\n" +
	"\rfinal_balance\x18\x01 \x01(\x03R\ffinalBalance\x12\x1d\n" +
	"\n" +
	"total_earn\x18\x02 \x01(\x03R\ttotalEarn\x12\x1f\n" +
	"\vtotal_spend\x18\x03 \x01(\x03R\n" +
	"totalSpend\x12\x1f\n" +
	"\vfish_killed\x18\x04 \x01(\x05R\n" +
	"fishKilled\x12\x1f\n" +
	"\vshots_fired\x18\x05 \x01(\x05R\n" +
	"shotsFired\"\xd3\x01\n" +
	"\x0eSpawnFishEvent\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\afish_id\x18\x02 \x01(\x05R\x06fishId\x12\x17\n" +
	"\apath_id\x18\x03 \x01(\x05R\x06pathId\x12\x1d\n" +
	"\n" +
	"spawn_time\x18\x04 \x01(\x03R\tspawnTime\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\x12\x14\n" +
	"\x05speed\x18\x06 \x01(\x02R\x05speed\x12\x1d\n" +
	"\n" +
	"asset_path\x18\a \x01(\tR\tassetPath\"n\n" +
	"\x13BroadcastShootEvent\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\x05R\x06seatId\x12\x13\n" +
	"\x05pos_x\x18\x02 \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x03 \x01(\x02R\x04posY\x12\x14\n" +
	"\x05angle\x18\x04 \x01(\x02R\x05angle\"N\n" +
	"\x12BroadcastKillEvent\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\aseat_id\x18\x02 \x01(\x05R\x06seatId\":\n" +
	"\n" +
	"ErrorEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\v\n" +
	"\tPongEvent\"\x89\a\n" +
	"\bEnvelope\x128\n" +
	"\tjoin_room\x18\x01 \x01(\v2\x19.fishgame.JoinRoomRequestH\x00R\bjoinRoom\x12A\n" +
	"\fclient_ready\x18\x02 \x01(\v2\x1c.fishgame.ClientReadyRequestH\x00R\vclientReady\x12.\n" +
	"\x05shoot\x18\x03 \x01(\v2\x16.fishgame.ShootRequestH\x00R\x05shoot\x125\n" +
	"\bhit_fish\x18\x04 \x01(\v2\x18.fishgame.HitFishRequestH\x00R\ahitFish\x12;\n" +
	"\n" +
	"leave_room\x18\x05 \x01(\v2\x1a.fishgame.LeaveRoomRequestH\x00R\tleaveRoom\x12+\n" +
	"\x04ping\x18\x06 \x01(\v2\x15.fishgame.PingRequestH\x00R\x04ping\x12H\n" +
	"\x0fsession_started\x18\n" +
	" \x01(\v2\x1d.fishgame.SessionStartedEventH\x00R\x0esessionStarted\x126\n" +
	"\tshoot_ack\x18\v \x01(\v2\x17.fishgame.ShootAckEventH\x00R\bshootAck\x129\n" +
	"\n" +
	"hit_result\x18\f \x01(\v2\x18.fishgame.HitResultEventH\x00R\thitResult\x12B\n" +
	"\rsession_ended\x18\r \x01(\v2\x1b.fishgame.SessionEndedEventH\x00R\fsessionEnded\x129\n" +
	"\n" +
	"spawn_fish\x18\x0e \x01(\v2\x18.fishgame.SpawnFishEventH\x00R\tspawnFish\x12H\n" +
	"\x0fbroadcast_shoot\x18\x0f \x01(\v2\x1d.fishgame.BroadcastShootEventH\x00R\x0ebroadcastShoot\x12E\n" +
	"\x0ebroadcast_kill\x18\x10 \x01(\v2\x1c.fishgame.BroadcastKillEventH\x00R\rbroadcastKill\x12,\n" +
	"\x05error\x18\x11 \x01(\v2\x14.fishgame.ErrorEventH\x00R\x05error\x12)\n" +
	"\x04pong\x18\x12 \x01(\v2\x13.fishgame.PongEventH\x00R\x04pongB\t\n" +
	"\apayloadB_ZLgithub.com/ptphat03/Fish-Game/services/game-server/internal/pb;fishgamepb\xaa\x02\x0eFishGame.Protob\x06proto3"

var (
	file_fish_game_proto_rawDescOnce sync.Once
	file_fish_game_proto_rawDescData []byte
)

func file_fish_game_proto_rawDescGZIP() []byte {
	file_fish_game_proto_rawDescOnce.Do(func() {
		file_fish_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fish_game_proto_rawDesc), len(file_fish_game_proto_rawDesc)))
	})
	return file_fish_game_proto_rawDescData
}

var file_fish_game_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_fish_game_proto_goTypes = []any{
	(*JoinRoomRequest)(nil),     // 0: fishgame.JoinRoomRequest
	(*ClientReadyRequest)(nil),  // 1: fishgame.ClientReadyRequest
	(*ShootRequest)(nil),        // 2: fishgame.ShootRequest
	(*HitFishRequest)(nil),      // 3: fishgame.HitFishRequest
	(*LeaveRoomRequest)(nil),    // 4: fishgame.LeaveRoomRequest
	(*PingRequest)(nil),         // 5: fishgame.PingRequest
	(*SessionStartedEvent)(nil), // 6: fishgame.SessionStartedEvent
	(*ShootAckEvent)(nil),       // 7: fishgame.ShootAckEvent
	(*HitResultEvent)(nil),      // 8: fishgame.HitResultEvent
	(*SessionEndedEvent)(nil),   // 9: fishgame.SessionEndedEvent
	(*SpawnFishEvent)(nil),      // 10: fishgame.SpawnFishEvent
	(*BroadcastShootEvent)(nil), // 11: fishgame.BroadcastShootEvent
	(*BroadcastKillEvent)(nil),  // 12: fishgame.BroadcastKillEvent
	(*ErrorEvent)(nil),          // 13: fishgame.ErrorEvent
	(*PongEvent)(nil),           // 14: fishgame.PongEvent
	(*Envelope)(nil),            // 15: fishgame.Envelope
}
var file_fish_game_proto_depIdxs = []int32{
	0,  // 0: fishgame.Envelope.join_room:type_name -> fishgame.JoinRoomRequest
	1,  // 1: fishgame.Envelope.client_ready:type_name -> fishgame.ClientReadyRequest
	2,  // 2: fishgame.Envelope.shoot:type_name -> fishgame.ShootRequest
	3,  // 3: fishgame.Envelope.hit_fish:type_name -> fishgame.HitFishRequest
	4,  // 4: fishgame.Envelope.leave_room:type_name -> fishgame.LeaveRoomRequest
	5,  // 5: fishgame.Envelope.ping:type_name -> fishgame.PingRequest
	6,  // 6: fishgame.Envelope.session_started:type_name -> fishgame.SessionStartedEvent
	7,  // 7: fishgame.Envelope.shoot_ack:type_name -> fishgame.ShootAckEvent
	8,  // 8: fishgame.Envelope.hit_result:type_name -> fishgame.HitResultEvent
	9,  // 9: fishgame.Envelope.session_ended:type_name -> fishgame.SessionEndedEvent
	10, // 10: fishgame.Envelope.spawn_fish:type_name -> fishgame.SpawnFishEvent
	11, // 11: fishgame.Envelope.broadcast_shoot:type_name -> fishgame.BroadcastShootEvent
	12, // 12: fishgame.Envelope.broadcast_kill:type_name -> fishgame.BroadcastKillEvent
	13, // 13: fishgame.Envelope.error:type_name -> fishgame.ErrorEvent
	14, // 14: fishgame.Envelope.pong:type_name -> fishgame.PongEvent
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_fish_game_proto_init() }
func file_fish_game_proto_init() {
	if File_fish_game_proto != nil {
		return
	}
	file_fish_game_proto_msgTypes[15].OneofWrappers = []any{
		(*Envelope_JoinRoom)(nil),
		(*Envelope_ClientReady)(nil),
		(*Envelope_Shoot)(nil),
		(*Envelope_HitFish)(nil),
		(*Envelope_LeaveRoom)(nil),
		(*Envelope_Ping)(nil),
		(*Envelope_SessionStarted)(nil),
		(*Envelope_ShootAck)(nil),
		(*Envelope_HitResult)(nil),
		(*Envelope_SessionEnded)(nil),
		(*Envelope_SpawnFish)(nil),
		(*Envelope_BroadcastShoot)(nil),
		(*Envelope_BroadcastKill)(nil),
		(*Envelope_Error)(nil),
		(*Envelope_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fish_game_proto_rawDesc), len(file_fish_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fish_game_proto_goTypes,
		DependencyIndexes: file_fish_game_proto_depIdxs,
		MessageInfos:      file_fish_game_proto_msgTypes,
	}.Build()
	File_fish_game_proto = out.File
	file_fish_game_proto_goTypes = nil
	file_fish_game_proto_depIdxs = nil
}
